# docker build .
# docker-compose up
# docker compose up --build -d

version: "2.0"

services:
  php-apache-environment:
    container_name: Host_One
    
    build: .

    ports: 
      - "8001:80"


